// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjlf7a_Mn7Ep1VnGaJl-ZOp_rlilXqNwY',
    appId: '1:802519688722:web:7a598af8bb8db7c6449acb',
    messagingSenderId: '802519688722',
    projectId: 'flutterparcial-3154e',
    authDomain: 'flutterparcial-3154e.firebaseapp.com',
    storageBucket: 'flutterparcial-3154e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClGIhru8FVIcwbA1vDEcDXLNEPS6MloYA',
    appId: '1:802519688722:android:4e8ef2cd50eb1d14449acb',
    messagingSenderId: '802519688722',
    projectId: 'flutterparcial-3154e',
    storageBucket: 'flutterparcial-3154e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjJXFpJ_8-CRpVTIqtINExP8DMYJQd2xA',
    appId: '1:802519688722:ios:fb123326bd694702449acb',
    messagingSenderId: '802519688722',
    projectId: 'flutterparcial-3154e',
    storageBucket: 'flutterparcial-3154e.appspot.com',
    iosClientId: '802519688722-hod6hnc7nbtima12ov5ibuvmv5sia88e.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjJXFpJ_8-CRpVTIqtINExP8DMYJQd2xA',
    appId: '1:802519688722:ios:65bec76027fb61b3449acb',
    messagingSenderId: '802519688722',
    projectId: 'flutterparcial-3154e',
    storageBucket: 'flutterparcial-3154e.appspot.com',
    iosClientId: '802519688722-hhtovhsjggoc8mlsgbsshk9nu4gp3kei.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial2.RunnerTests',
  );
}
